// <auto-generated />
using System;
using GameDayParty.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GameDayParty.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251217204125_AddUpvoteCount")]
    partial class AddUpvoteCount
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GameDayParty.Models.Event", b =>
                {
                    b.Property<int>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EventId"));

                    b.Property<DateTime>("EventDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EventName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("GameDetails")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HostName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("HostUserId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsFinalized")
                        .HasColumnType("boolean");

                    b.HasKey("EventId");

                    b.ToTable("Events");

                    b.HasData(
                        new
                        {
                            EventId = 1,
                            EventDate = new DateTime(2025, 12, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            EventName = "Sunday Night Football Fiesta",
                            GameDetails = "Packers vs. Vikings (NFC North)",
                            HostName = "Jared Slone",
                            HostUserId = 0,
                            IsFinalized = false
                        });
                });

            modelBuilder.Entity("GameDayParty.Models.FoodSuggestion", b =>
                {
                    b.Property<int>("FoodSuggestionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("FoodSuggestionId"));

                    b.Property<int>("EventId")
                        .HasColumnType("integer");

                    b.Property<string>("FoodCategory")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FoodName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsVegetarian")
                        .HasColumnType("boolean");

                    b.Property<string>("SuggestedByName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UpvoteCount")
                        .HasColumnType("integer");

                    b.HasKey("FoodSuggestionId");

                    b.HasIndex("EventId");

                    b.ToTable("FoodSuggestions");

                    b.HasData(
                        new
                        {
                            FoodSuggestionId = 1,
                            EventId = 1,
                            FoodCategory = "",
                            FoodName = "Buffalo Wings",
                            IsVegetarian = false,
                            SuggestedByName = "Jared",
                            UpvoteCount = 0
                        });
                });

            modelBuilder.Entity("GameDayParty.Models.FoodSuggestion", b =>
                {
                    b.HasOne("GameDayParty.Models.Event", "Event")
                        .WithMany("FoodSuggestions")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("GameDayParty.Models.Event", b =>
                {
                    b.Navigation("FoodSuggestions");
                });
#pragma warning restore 612, 618
        }
    }
}
